services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    volumes:
      - tasks_db_prod:/var/lib/postgresql/data
    env_file:
      - ./.envs/db.env
    ports:
      - 5432:5432

  scheduler:
    build:
      dockerfile: ./Dockerfile
      context: .
    entrypoint: ./bin/scheduler
    env_file:
      - ./.envs/scheduler.env
    ports:
      - 8000:8000
    depends_on:
      - db

  worker:
    build:
      dockerfile: ./Dockerfile
      context: .
    entrypoint: ./bin/worker
    env_file:
      - ./.envs/worker.env
    environment:
      WORKER_ADDR: worker:9000
    depends_on:
      - db
      - scheduler

volumes:
  tasks_db_prod:
