services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    volumes:
      - tasks_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/db.env
    ports:
      - 5432:5432

  scheduler:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    entrypoint: air -c ./.air.scheduler.toml
    env_file:
      - ./.envs/scheduler.env
    volumes:
      - .:/app
    ports:
      - 8000:8000

  worker:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    entrypoint: air -c ./.air.worker.toml
    env_file:
      - ./.envs/worker.env
    environment:
      WORKER_ADDR: worker:9000
    volumes:
      - .:/app

volumes:
  tasks_db:
